# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1ed0f32ca65b87c4a918a5973359900e2c26f1d5de70dcc59a949de1e810cd529a259a225a7277e54214637a5bdfc7e9a88ef361f660947c4e558e99677cf1

test:
  secret_key_base: e887867b5d668accef6c328c68d8b4395b3a6326480249f675592582a5f596049dc4a3cfcf8f7a0c98d7eacdfd136416e5dee67574d5ba7176e7cfa49f4ffe2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
